### ISSUE TITLE
Via Marker position der Frequenzen auf der Karte bestimmen

### ISSUE THREAD

**Issue by MasaruKondera** [gruppe-adler/CO_Template.VR#19]
Im moment ist es unmöglich die Frequenzen auf der Kate zu verschieben.

Lösunsansatz: Marker mit bestimmen Variablennamen plazieren und die Frequenzen an der stelle dieses Markers platzieren. Soll ermöglichen Frequenzen z.b. direkt neben der Base zu plazieren.

**Comment by McDiod** [comment]
1e224601c9364a964a9c200bd567fd37107a70e6
