### ISSUE TITLE
Loadouts erstellen

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/CO_Template.VR#3]
- [x] Bundeswehr Flecktarn
- [x] Bundeswehr Tropentarn
- [x] US Army OCP
- [x] US Army UCP
- [x] US Marines Marpat
- [x] Rus. MSV Flora
- [x] Rus. MSV EMR

(edit: Fussels Liste ersetzt)

**Comment by Fusselwurm** [comment]
glaub nich ob wir soviel wollen... habs nur aus den missionparametern übernommen die woanders irgendwo definiert sind :trollface:

**Comment by McDiod** [comment]
Feedback von AK:
Ausrüstungsslots:
Es fehlen Nachtsichtgerät, Schalldämpfer bei Gewehr und Pistole, Zweibein fürs Gewehr, Laser-Licht-Modul.

Uniform: Es fehlt das Schanzwerkzeug und die Taschenlampe zum Kartenlesen bei Nacht. Brauchen wir die Ohrenstöpsel noch?

Weste: Sehr gut, dass Munition und Granaten in der Weste gesammelt werden und die Uniform davon frei bleibt.

Sonnenbrille: Warum gibt es unterschiedliche Sonnenbrillen für unterschiedliche Rollen?

individualisierung: Wahrscheinlich geht es über die Möglichkeiten einer solchen Vorlage hinaus, aber ich würde mich über persönliche Individualisierungsmöglichkeiten der Uniform freuen. Dazu eignen sich Dinge wie Halstücher, Gesichtsmasken, Brillen und in meinem Fall der Helm. Wenn das Standardloadout die “Gesichtsbedeckung” vorschreibt, funktionieren im Spielerprofil eingetragene individuelle Brillen und Masken nicht, glaube ich. Darum würde ich im Standardloadout auf Brillen verzichten. Wenn das nicht geht, dann kann die Brille vielleicht im Gepäck Platz finden.
