### ISSUE TITLE
Missionsparameter --> USERSCRIPTS

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/CO_Template.VR#4]
Sind die Missionsparameter irgendwo eingebunden @fry-grad ? Ich finde nicht wo.
Die allgemeinen Sachen können komplett raus (die stellt man ja eher im Editor ein) und der Rest sollte am besten über die userscripts\missionsettings.sqf fix eingestellt werden. Am Ende soll ja keine dynamische Mission herauskommen, bei der man erst noch in der Lobby die Parameter auswählt.

c4only, soundplay, nighteffect, autoresppos, autodelete hört sich ganz interessant an.

Der Corpse Manager wird hier schon eingestellt:
https://github.com/gruppe-adler/CO_Template.Stratis/blob/master/description.ext#L22
Also können die letzten beiden Parameter auch komplett raus, was?

https://github.com/gruppe-adler/CO_Template.Stratis/blob/master/ga_system/sys_config/params.hpp

**Comment by fry-grad** [comment]
ein paar Sachen können wir raus nehmen! 

factionselector
difficulty
c4only
soundplay
nighteffect
autodelete

würde ich gerne drin lassen, da es teilweise schon verwendet wird und in Zukunft auch eine Rolle spielen wird!

**Comment by McDiod** [comment]
erstmal deaktiviert
