### ISSUE TITLE
Loadout Issues

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/CO_Template.VR#41]
Is there any chance grad loadout might trigger even when no faction is set (empty strings)?

If not, we can rule out grad loadout as the cause for the "no uniform" problem and should consider other factors.

Might be necessary to double check with a mission not using grad loadout at all. Problem doesn't trigger everytime – couldnt reproduce alone on dedicated in same mission.

**Comment by McDiod** [comment]
I checked this with `_this getVariable "grad_loadout_applicationCount"` ([grad_loadout_fnc_doLoadout](https://github.com/gruppe-adler/grad-loadout/blob/master/functions/general/fn_doLoadout.sqf#L36)). Function doesn't run if no loadout is selected for faction.

**Comment by nomisum** [comment]
ownerChanges seem to play a significant role in "naked" spawning. I think it has to be BIS fault.
