### ISSUE TITLE
initServer.sqf durch USER Ordner zugänglich machen

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/CO_Template.VR#48]
Es wär schön, wenn man analog zur `userInit.sqf` im User Ordner auch eine Datei hat, die "Zugriff" auf die `initServer.sqf` ermöglicht.

**Comment by nomisum** [comment]
userInit wird auch auf Server ausgeführt

**Comment by DerZade** [comment]
Ja das ist mir schon klar, aber dann muss ich es immer in ein `isServer` schieben :/
Wär einfach nur schön das der Übersicht halber das getrennt haben zu können.

**Comment by McDiod** [comment]
Will ungern noch mehr Zeug im USER Ordner haben, schreckt irgendwann ab.
