### ISSUE TITLE
[discussion] make debug chat on demand and admin only

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/CO_Template.VR#52]
i find myself manually commenting out all the systemchat messages done by 
* radiosettings
* group settings
* grad loadout
(out of obvious reasons: not to interfere with intro cinematics)

maybe its better to make them opt-in and admin only? opinions?

**Comment by McDiod** [comment]
The radiosettings and groupsettings messages add nothing of value anyways. Can be removed completely imo.

**Comment by DerZade** [comment]
I agree. The same applies for the grad-loadout logs imho. For non admins the info that the loadout was applies etc. is just needless.

**Comment by McDiod** [comment]
https://github.com/gruppe-adler/grad-loadout/pull/44
