### ISSUE TITLE
vehicle radios get b0rked for players without backpack radio in their loadout

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/CO_Template.VR#64]
# symptom

Player will get an error "Resource not found" the first time they try to open the vehicle radio. The interface will not open.
An RPT entry like this is being produced:

```
16:43:45 Warning Message: Resource  not found
16:43:45  ➥ Context: 
16:43:45 	[] L1 ()
	[] L1 ()
	[] L78 (x\cba\addons\events\fnc_keyHandlerDown.sqf)
	[] L51 (x\cba\addons\events\fnc_keyHandlerDown.sqf)
	[] L70 (x\cba\addons\events\fnc_keyHandlerDown.sqf)
	[] L75 (x\cba\addons\events\fnc_keyHandlerDown.sqf)
	[] L75 (x\cba\addons\events\fnc_keyHandlerDown.sqf)
	[] L4 (z\tfar\addons\core\functions\flexiUI\flexiInit.sqf)
	[] L18 (x\cba\addons\ui\flexiMenu\fnc_openMenuByDef.sqf)
	[] L29 (x\cba\addons\ui\flexiMenu\fnc_openMenuByDef.sqf)
	[] L81 (x\cba\addons\ui\flexiMenu\fnc_openMenuByDef.sqf)
	[] L89 (x\cba\addons\ui\flexiMenu\fnc_openMenuByDef.sqf)
	[] L91 (x\cba\addons\ui\flexiMenu\fnc_openMenuByDef.sqf)
	[] L102 (x\cba\addons\ui\flexiMenu\fnc_menu.sqf)
	[] L70 (x\cba\addons\ui\flexiMenu\fnc_getMenuDef.sqf)
	[] L39 (x\cba\addons\ui\flexiMenu\fnc_getMenuDef.sqf)
	[] L47 (x\cba\addons\ui\flexiMenu\fnc_getMenuDef.sqf)
	[] L52 (x\cba\addons\ui\flexiMenu\fnc_getMenuDef.sqf)
	[] L1 ()
	[] L4 (z\tfar\addons\core\functions\flexiUI\fnc_lrRadioMenu.sqf)
	[] L37 (z\tfar\addons\core\functions\fle
```

# problem

players who do not have a backpack radio defined via grad-loadout cannot open vehicle radio settings in airborne vehicles that do not have an explicit TFAR radio class.

## bad code

problematic code here:

https://github.com/gruppe-adler/CO_Template.VR/blob/master/functions/radiosettings/fn_setDefaultRadios.sqf#L5-L13

```
_radios = [player] call GRAD_radiosettings_fnc_getLoadoutRadios;
_radios params ["_shortrange", "_longrange"];
TFAR_DefaultRadio_Backpack_West         = _longrange;
// ...
TFAR_DefaultRadio_Airborne_West         = _longrange;
```

with https://github.com/gruppe-adler/CO_Template.VR/blob/master/functions/radiosettings/fn_getLoadoutRadios.sqf#L16

```
if (_longrange find "tf_" != 0) then {_longrange = ""};
```

^also, this uses the old tfar-prefix

This effectively sets `TFAR_DefaultRadio_Airborne_West = "";` for players without long-range radio in their loadout (so... those that need it!) , which breaks TFAR in all vehicles that have not an explicitly set radio class [(either via config or variable)](https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/addons/core/functions/fnc_getLrRadioProperty.sqf#L36-L40)

**Comment by Fusselwurm** [comment]
first question: why do we want to change the airborne radios at all?

**Comment by McDiod** [comment]
We don't. I was probably thinking these were backpack type radios for paratroopers 🙈

**Comment by Fusselwurm** [comment]
and while I'm at it, why do we want to set `TFAR_DefaultRadio_Backpack_West` etc ? Shouldnt the normal grad-factions / grad-loadout be enough? Why override the TFAR defaults?

**Comment by McDiod** [comment]
It used to be that people spawned with the wrong radios (remember Zeus having to spawn crates with radios at the start of our missions?). I'm not sure if that's still an issue that would happen without this workaround.

**Comment by nomisum** [comment]
hmmm maybe could be solved differently by reapplying / checking loadout after some delay. my guess is some race condition in init of tfar/template where tfar defines default radios *after* loadout has been applied.

**Comment by Fusselwurm** [comment]
ok, so we'd need to think about it and test it extensively. :grimacing: 

Let's just fix the airborne vehicle thing for now, and postpone everything else.

**Comment by Fusselwurm** [comment]
> It used to be that people spawned with the wrong radios (remember Zeus having to spawn crates with radios at the start of our missions?). I'm not sure if that's still an issue that would happen without this workaround.

As far as I can see, https://github.com/gruppe-adler/TvT_Template.VR does not change the TFAR default radios, and we haven't had related problems in TvTs, have we?
