### ISSUE TITLE
Fancy Holy Shit Loading Pic

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/CO_Template.VR#7]
Ich weiß, Endgame ist auch noch offen.

Hier hab ich aber schon eine kühle Idee 👯 

Details asap

**Comment by nomisum** [comment]
@McDiod was hältste davon?
![blueprint](https://cloud.githubusercontent.com/assets/500164/18406187/0f95a7f0-76fa-11e6-9027-52756f12647e.png)

**Comment by McDiod** [comment]
Top! :+1:
